### ISSUE TITLE
Taskbar instances present in alt-tab switcher list

### ISSUE THREAD

**Issue by Jikeh** [ChrisAnd1998/TaskbarX#542]
Not sure if a bug or intended, but I haven't found anyone talking about it on here.
As the screenshot shows, the two taskbars are present in the alt-tab switcher list (as I have 2 monitors). I'm using the Rainmeter version, but it happens with the stand-alone version as well. Apart from the animation type and speed, the settings are standard. 
Is this behavior intended? If so, is there any way I can remove them from the list? 

**To Reproduce**
Simply have TaskbarX running and press Alt+Tab.

**Expected behavior**
I'd rather not have the two taskbars in the list.

**Screenshots**
![taskbarscreenshot2](https://user-images.githubusercontent.com/13394868/106394439-e2a05980-63fc-11eb-822d-e6f5e486be47.png)

**System:**
 - Windows 10 PRO 1909
 - TaskbarX version: 1.6.5.0 (Rainmeter version)

**Comment by birbbbbb** [comment]
I'm having the same issue, I just have one taskbar, the problem also appears in task view.  1.6.5.0 (non-Rainmeter) Windows 10 Home 20H2

**Comment by ChrisAnd1998** [comment]
@Jikeh @birbbbbb Weird are you both sure this is TaskbarX? TaskbarX runs in the background moving the original taskbar. There is no gui or windows created. So it can't be TaskbarX showing there because there is nothing to display...

**Comment by birbbbbb** [comment]
> @Jikeh @birbbbbb Weird are you both sure this is TaskbarX? TaskbarX runs in the background moving the original taskbar. There is no gui or windows created. So it can't be TaskbarX showing there because there is nothing to display... It also shows a default application icon not TaskbarX's.

I'm very sure it is TaskbarX, if I uninstall the application, then restart my computer the issue won't happen. I downgraded to 1.6.4.0 and the issue was entirely gone. I think it is only  a problem with the most recent build.

**Comment by Jikeh** [comment]
> @Jikeh @birbbbbb Weird are you both sure this is TaskbarX? TaskbarX runs in the background moving the original taskbar. There is no gui or windows created. So it can't be TaskbarX showing there because there is nothing to display... It also shows a default application icon not TaskbarX's.

I'm positive, downloaded it from the Releases page. I can confirm that 1.6.4 does not present this problem. Loading 1.6.5 right after unloading 1.6.4 adds the taskbars to the alt-tab list. Killing the process doesn't seem to fix it, signing out is required. I can provide more info/logs/whatever might help to pinpoint the problem.

**Comment by BitGrub** [comment]
Same here. Stopping taskbarX didn't remove it, but uninstalling and restarting my PC fixed it. Using the UWP version, if that makes a difference

**Comment by BitGrub** [comment]
Reinstalled it and the issue wasn't present immediately, but by the time I changed the animation and animation speed to backeaseinout 1000, it came back. Closing the taskbar "window" from the alt tab screen displays a legit power menu I've never seen in Windows before

![2021-01-31 (1)](https://user-images.githubusercontent.com/20694416/106400323-88f85900-6415-11eb-8045-a296bf2cf257.png)

**Comment by fxzxmicah** [comment]
Consistent with these issues:
https://github.com/ChrisAnd1998/TaskbarX/issues/539
https://github.com/ChrisAnd1998/TaskbarX/issues/540

**Comment by Eduardodelpozzo** [comment]
I'm having the same issue. I have 
4 virtual desktops, and the taskbar is not showing in anyone but the default desktop.
------------------------------------------------------------------------------------------------------
![Captura de pantalla 2021-01-31 204745](https://user-images.githubusercontent.com/45251706/106409226-b3421a80-6405-11eb-82fd-a4ca3c74227d.png)
![Captura de pantalla 2021-01-31 204904](https://user-images.githubusercontent.com/45251706/106409323-e97f9a00-6405-11eb-9e70-eb3d629a7b4b.png)
![Captura de pantalla 2021-01-31 204948](https://user-images.githubusercontent.com/45251706/106409325-eab0c700-6405-11eb-8b73-c7a045f78281.png)

**Comment by ChrisAnd1998** [comment]
Allright, i will find out whats going on here..

**Comment by daviiiiiid** [comment]
I'll +1 again as I upgraded to the latest version yesterday and it started happening. Only upgraded because I was on an older version that started giving me errors when booting. Good to see it is being acknowledged! Thanks

**Comment by ChrisAnd1998** [comment]
Allright, i was able to reproduce it. Should be fixed now in the pre-release.
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.6.6.0

**Comment by BitGrub** [comment]
Good to hear. How long does it usually take for a release to make it to the windows store?

**Comment by ChrisAnd1998** [comment]
About 3 business days after i put it in release. Currently it's in pre-release until i think it's ready.

**Comment by Iipal** [comment]
It's not fixed yet. After running the fullscreen app this bug appears again. And when after pressing "Apply" settings from TaskbarX Configurator.
![tf](https://user-images.githubusercontent.com/31858171/106990625-6e7df280-6729-11eb-94a1-44381fee7cb1.png)

**Comment by Iipal** [comment]
And it's focusing on a taskbar when opening fullscreen apps, and they immediately hiding because of this. @ChrisAnd1998

**Comment by BitGrub** [comment]
It really is the most frustrating bug to deal with.

**Comment by uwagura** [comment]
I am still having this issue with version 1.7.6.0.

I'm not sure if it's related, but before noticing this problem, TaskBarX usually starts switching rapidly between working and not working. Here's a video of the behavior that began just before I noticed the new taskbar instances in my alt-tab switcher list

https://github.com/ChrisAnd1998/TaskbarX/assets/36386988/db8cc10a-2873-486d-9bd1-4a44d24f4666

**Comment by Iipal** [comment]
Hello, by warp I meant exactly that issues with bottom rows 1.5u, but I
just got new keyboard, and tested this keycap set again, apparently this
was my mistake with soldering keyboard, on hotswap with multiple different
switches it was matter of stem wobble rather than the keycap issue...

But I still have missing Home key, but x2 PgUp, all the proofs I'll attach
to this email.

Also from the same order I have KeyKobo White on Black which is missing R3
1.75 Control key, but instead have x2 R3 1.75u Function keys.

*Olive R2 is from another vendor, so don't worry about it, but yes, those
1.5u actually warped

Order #: NK_446549

But I must to clarify, that it's were ordered by another person. The math
is simple: We live in Ukraine, there is no direct shipping or it is way to
expesnive rather than just using proxy services, so we are ordering stuff
together and splitting the shipping cost. So that why you were not able to
find Mictaln order under my email. But this Mictlan and KKB WoB keycaps are
from this particular Order #.


*all photo proofs I'll attach to this email.
 PXL_20240103_015414747~2.jpg
<https://drive.google.com/file/d/1e-vRSGFlJUxdBAHpdlM8-8C5cwUr8LHz/view?usp=drive_web>
 PXL_20240103_015422885~2.jpg
<https://drive.google.com/file/d/1-jg0FJ15lhfIeZQgKlW6K5mxzlT0tW8r/view?usp=drive_web>
 PXL_20240103_015531176~2.jpg
<https://drive.google.com/file/d/1dQlL_dyb1iV2cQQPeP4wIHzGhsMJvMtu/view?usp=drive_web>
 PXL_20240103_015631527~2.jpg
<https://drive.google.com/file/d/1qhRMQF8mFcFJQ94XJlktDe46ghtBAEL-/view?usp=drive_web>
 PXL_20240103_015818829.jpg
<https://drive.google.com/file/d/1hm9JPM5gzoLVy3TIOu7VAIK4slrMOyMH/view?usp=drive_web>
 PXL_20240103_015835426.jpg
<https://drive.google.com/file/d/1x4aDbNpNlTo_o56Rpz7CiNnoOHkdj_no/view?usp=drive_web>
 PXL_20240103_015852780~2.jpg
<https://drive.google.com/file/d/1jSFDx5g1RC31v1TxzWl8wkJ1HC3kwN-X/view?usp=drive_web>
 PXL_20240103_172213986~2.jpg
<https://drive.google.com/file/d/1VXIZ6vVyOMhDQUS3dqGNw-EOWw6g1GIg/view?usp=drive_web>
