### ISSUE TITLE
[bug] windows 10: taskbar on top

### ISSUE THREAD

**Issue by leminsc8er** [ChrisAnd1998/TaskbarX#86]
old window7-10 bug but falconx can fix it maybe
- [if taskbar blend out is activate] delay blend in if taskbar on top
- If app into focus the taskbar will does not blend out... pleas force blend out after timeout!
- Fix or Relod taskbar if app-window is behind the taskbar with "close, minimize, resize" or set app-window on top after delay or focus if windows 10 options "taskbar on top" https://i.imgur.com/R7gBggr.png

**Comment by Martin5001** [comment]
If it is "old window7-10 bug" then I think it should be fixed by Microsoft, not the app. (Because if Microsoft eventually fixes it in the future, it could break the app.)
I personally don´t understand what bug @leminsc8er means, but if you do, then probably you can try contacting MS first.

**Comment by leminsc8er** [comment]
you right but Microsoft don't fix it.
this bug is exist since you can add taskbart on top ...befor windows 7?!
 but i understand what you mean.

**Comment by leminsc8er** [comment]
add bug screen **https://imgur.com/gallery/LM12yL9**

**Comment by leminsc8er** [comment]
> 
> 
> If it is "old window7-10 bug" then I think it should be fixed by Microsoft, not the app. (Because if Microsoft eventually fixes it in the future, it could break the app.)
> I personally don´t understand what bug @leminsc8er means, but if you do, then probably you can try contacting MS first.

not fixed yet ;-) may it come with win 10 x?
this will fixed the problem <3 https://chrisandriessen.nl/aerial
